import pymel.core as pm
#中心部
pm.parent( 'root_trs', 'ctrl_grp' )
pm.parent( 'root_ctrl', 'root_trs' )
pm.parent( 'handIK_trs_L','footIK_trs_L','COG_trs', 'root_ctrl' )
pm.parent( 'COG_ctrl','COG_trs' )
pm.parent( 'upLegFK_trs_R','upLegFK_trs_L','spine01_trs','COG_ctrl' )
pm.parent( 'spine01_ctrl','spine01_trs' )
pm.parent( 'spine02_trs', 'spine01_ctrl' )
pm.parent( 'spine02_ctrl','spine02_trs' )
pm.parent( 'spine03_trs', 'spine02_ctrl' )
pm.parent( 'spine03_ctrl','spine03_trs' )
pm.parent( 'shoulder_trs_L','shoulder_trs_R','neck_trs','spine03_ctrl' )
pm.parent( 'neck_ctrl','neck_trs' )
pm.parent( 'head_trs','neck_ctrl' )
pm.parent( 'head_ctrl','head_trs' )
#左腕FK
pm.parent( 'sholuder_ctrl_L','sholuder_trs_L' )
pm.parent( 'upArmFK_trs_L','sholuder_ctrl_L' )
pm.parent( 'upArmFK_ctrl_L','upArmFK_trs_L' )
pm.parent( 'lowArmFK_trs_L','upArmFK_ctrl_L' )
pm.parent( 'lowArmFK_ctrl_L','lowArmFK_trs_L' )
pm.parent( 'handFK_trs_L','lowArmFK_ctrl_L' )
pm.parent( 'handFK_ctrl_L','handFK_trs_L' )
pm.parent( 'little01FK_trs_L','ring01FK_trs_L','middle01FK_trs_L','index01FK_trs_L','thumb01FK_trs_L','handFK_ctrl_L' )
pm.parent( 'thumb01FK_ctrl_L','thumb01FK_trs_L' )
pm.parent( 'thumb02FK_trs_L', 'thumb01FK_ctrl_L' )
pm.parent( 'thumb02FK_ctrl_L','thumb02FK_trs_L' )
pm.parent( 'thumb03FK_trs_L', 'thumb02FK_ctrl_L' )
pm.parent( 'thumb03FK_ctrl_L','thumb03FK_trs_L' )
pm.parent( 'index01FK_ctrl_L','index01FK_trs_L' )
pm.parent( 'index02FK_trs_L', 'index01FK_ctrl_L' )
pm.parent( 'index02FK_ctrl_L','index02FK_trs_L' )
pm.parent( 'index03FK_trs_L', 'index02FK_ctrl_L' )
pm.parent( 'index03FK_ctrl_L','index03FK_trs_L' )
pm.parent( 'middle01FK_ctrl_L','middle01FK_trs_L' )
pm.parent( 'middle02FK_trs_L', 'middle01FK_ctrl_L' )
pm.parent( 'middle02FK_ctrl_L','middle02FK_trs_L' )
pm.parent( 'middle03FK_trs_L', 'middle02FK_ctrl_L' )
pm.parent( 'middle03FK_ctrl_L','middle03FK_trs_L' )
pm.parent( 'ring01FK_ctrl_L','ring01FK_trs_L' )
pm.parent( 'ring02FK_trs_L', 'ring01FK_ctrl_L' )
pm.parent( 'ring02FK_ctrl_L','ring02FK_trs_L' )
pm.parent( 'ring03FK_trs_L', 'ring02FK_ctrl_L' )
pm.parent( 'ring03FK_ctrl_L','ring03FK_trs_L' )
pm.parent( 'little01FK_ctrl_L','little01FK_trs_L' )
pm.parent( 'little02FK_trs_L', 'little01FK_ctrl_L' )
pm.parent( 'little02FK_ctrl_L','little02FK_trs_L' )
pm.parent( 'little03FK_trs_L', 'little02FK_ctrl_L' )
pm.parent( 'little03FK_ctrl_L','little03FK_trs_L' )
#右腕FK
pm.parent( 'sholuder_ctrl_R','sholuder_trs_R' )
pm.parent( 'upArmFK_trs_R','sholuder_ctrl_R' )
pm.parent( 'upArmFK_ctrl_R','upArmFK_trs_R' )
pm.parent( 'lowArmFK_trs_R','upArmFK_ctrl_R' )
pm.parent( 'lowArmFK_ctrl_R','lowArmFK_trs_R' )
pm.parent( 'handFK_trs_R','lowArmFK_ctrl_R' )
pm.parent( 'handFK_ctrl_R','handFK_trs_R' )
pm.parent( 'little01FK_trs_R','ring01FK_trs_R','middle01FK_trs_R','index01FK_trs_R','thumb01FK_trs_R','handFK_ctrl_R' )
pm.parent( 'thumb01FK_ctrl_R','thumb01FK_trs_R' )
pm.parent( 'thumb02FK_trs_R', 'thumb01FK_ctrl_R' )
pm.parent( 'thumb02FK_ctrl_R','thumb02FK_trs_R' )
pm.parent( 'thumb03FK_trs_R', 'thumb02FK_ctrl_R' )
pm.parent( 'thumb03FK_ctrl_R','thumb03FK_trs_R' )
pm.parent( 'index01FK_ctrl_R','index01FK_trs_R' )
pm.parent( 'index02FK_trs_R', 'index01FK_ctrl_R' )
pm.parent( 'index02FK_ctrl_R','index02FK_trs_R' )
pm.parent( 'index03FK_trs_R', 'index02FK_ctrl_R' )
pm.parent( 'index03FK_ctrl_R','index03FK_trs_R' )
pm.parent( 'middle01FK_ctrl_R','middle01FK_trs_R' )
pm.parent( 'middle02FK_trs_R', 'middle01FK_ctrl_R' )
pm.parent( 'middle02FK_ctrl_R','middle02FK_trs_R' )
pm.parent( 'middle03FK_trs_R', 'middle02FK_ctrl_R' )
pm.parent( 'middle03FK_ctrl_R','middle03FK_trs_R' )
pm.parent( 'ring01FK_ctrl_R','ring01FK_trs_R' )
pm.parent( 'ring02FK_trs_R', 'ring01FK_ctrl_R' )
pm.parent( 'ring02FK_ctrl_R','ring02FK_trs_R' )
pm.parent( 'ring03FK_trs_R', 'ring02FK_ctrl_R' )
pm.parent( 'ring03FK_ctrl_R','ring03FK_trs_R' )
pm.parent( 'little01FK_ctrl_R','little01FK_trs_R' )
pm.parent( 'little02FK_trs_R', 'little01FK_ctrl_R' )
pm.parent( 'little02FK_ctrl_R','little02FK_trs_R' )
pm.parent( 'little03FK_trs_R', 'little02FK_ctrl_R' )
pm.parent( 'little03FK_ctrl_R','little03FK_trs_R' )
#左足FK
pm.parent( 'upLegFK_ctrl_L','upLegFK_trs_L' )
pm.parent( 'lowLegFK_trs_L','upLegFK_ctrl_L' )
pm.parent( 'lowLegFK_ctrl_L','lowLegFK_trs_L' )
pm.parent( 'ankleFK_trs_L','lowLegFK_ctrl_L' )
pm.parent( 'ankleFK_ctrl_L','ankleFK_trs_L' )
pm.parent( 'footFK_trs_L','ankleFK_ctrl_L' )
pm.parent( 'footFK_ctrl_L','footFK_trs_L' )
#右足FK
pm.parent( 'upLegFK_ctrl_R','upLegFK_trs_R' )
pm.parent( 'lowLegFK_trs_R','upLegFK_ctrl_R' )
pm.parent( 'lowLegFK_ctrl_R','lowLegFK_trs_R' )
pm.parent( 'ankleFK_trs_R','lowLegFK_ctrl_R' )
pm.parent( 'ankleFK_ctrl_R','ankleFK_trs_R' )
pm.parent( 'footFK_trs_R','ankleFK_ctrl_R' )
pm.parent( 'footFK_ctrl_R','footFK_trs_R' )
#左足IK
pm.parent( 'footIK_grp_L','footIK_ctrl_L','footIK_trs_L' )
pm.parent( 'lowLegIK_trs_L','footIK_trs_LT','footIK_ctrl_L' )
pm.parent( 'footIK_ctrl_LT','footIK_trs_LT' )
pm.parent( 'peelHell_trs_L','torTap_trs_L','footIK_ctrl_LT' )
pm.parent( 'toeTap_ctrl_L','torTap_trs_L' )
pm.parent( 'peelHell_ctrl_L','peelHell_trs_L' )
pm.parent( 'lowLegIK_ctrl_L','lowLegIK_trs_L' )
pm.parent( 'footIK_grp_LT','footIK_grp_L' )
pm.parent( 'toeTap_grp_L','peelHell_grp_L','footIK_grp_LT' )
pm.parent( 'toeTap_grp_L','peelHell_grp_L','footIK_grp_LT' )
#左腕IK
pm.parent( 'handIK_grp_L','handIK_ctrl_L','handIK_trs_L' )
pm.parent( 'handIK_grp_L','handIK_ctrl_L','handIK_trs_L' )
pm.parent( 'lowArmIK_trs_L','handIK_trs_LT','handIK_ctrl_L' )
pm.parent( 'handIK_ctrl_LT','handIK_trs_LT' )
pm.parent( 'thumbIK_trs_LT','thumbIK_trs_L','indexIK_trs_LT','indexIK_trs_L','middleIK_trs_LT','middleIK_trs_L','ringIK_trs_LT','ringIK_trs_L','littleIK_trs_LT','littleIK_trs_L','handIK_ctrl_LT' )
pm.parent( 'littleIK_ctrl_L','littleIK_trs_L' )
pm.parent( 'littleIK_ctrl_LT','littleIK_trs_LT' )
pm.parent( 'ringIK_ctrl_L','ringIK_trs_L' )
pm.parent( 'ringIK_ctrl_LT','ringIK_trs_LT' )
pm.parent( 'middleIK_ctrl_L','middleIK_trs_L' )
pm.parent( 'middleIK_ctrl_LT','middleIK_trs_LT' )
pm.parent( 'indexIK_ctrl_L','indexIK_trs_L' )
pm.parent( 'indexIK_ctrl_LT','indexIK_trs_LT' )
pm.parent( 'thumbIK_ctrl_L','thumbIK_trs_L' )
pm.parent( 'thumbIK_ctrl_LT','thumbIK_trs_LT' )
pm.parent( 'lowArmIK_ctrl_L','lowArmIK_trs_L' )
pm.parent( 'handIK_grp_LT','handIK_grp_L' )
pm.parent( 'littleIK_grp_L','ringIK_grp_L','middleIK_grp_L','indexIK_grp_L','thumbIK_grp_L','handIK_grp_LT')
#右足IK
pm.parent( 'footIK_grp_R','footIK_ctrl_R','footIK_trs_R' )
pm.parent( 'lowLegIK_trs_R','footIK_trs_RT','footIK_ctrl_R' )
pm.parent( 'footIK_ctrl_RT','footIK_trs_RT' )
pm.parent( 'peelHell_trs_R','torTap_trs_R','footIK_ctrl_RT' )
pm.parent( 'toeTap_ctrl_R','torTap_trs_R' )
pm.parent( 'peelHell_ctrl_R','peelHell_trs_R' )
pm.parent( 'lowLegIK_ctrl_R','lowLegIK_trs_R' )
pm.parent( 'footIK_grp_RT','footIK_grp_R' )
pm.parent( 'toeTap_grp_R','peelHell_grp_R','footIK_grp_RT' )
pm.parent( 'toeTap_grp_R','peelHell_grp_R','footIK_grp_RT' )
#右腕IK
pm.parent( 'handIK_grp_R','handIK_ctrl_R','handIK_trs_R' )
pm.parent( 'handIK_grp_R','handIK_ctrl_R','handIK_trs_R' )
pm.parent( 'lowArmIK_trs_R','handIK_trs_RT','handIK_ctrl_R' )
pm.parent( 'handIK_ctrl_RT','handIK_trs_RT' )
pm.parent( 'thumbIK_trs_RT','thumbIK_trs_R','indexIK_trs_RT','indexIK_trs_R','middleIK_trs_RT','middleIK_trs_R','ringIK_trs_RT','ringIK_trs_R','littleIK_trs_RT','littleIK_trs_R','handIK_ctrl_RT' )
pm.parent( 'littleIK_ctrl_R','littleIK_trs_R' )
pm.parent( 'littleIK_ctrl_RT','littleIK_trs_RT' )
pm.parent( 'ringIK_ctrl_R','ringIK_trs_R' )
pm.parent( 'ringIK_ctrl_RT','ringIK_trs_RT' )
pm.parent( 'middleIK_ctrl_R','middleIK_trs_R' )
pm.parent( 'middleIK_ctrl_RT','middleIK_trs_RT' )
pm.parent( 'indexIK_ctrl_R','indexIK_trs_R' )
pm.parent( 'indexIK_ctrl_RT','indexIK_trs_RT' )
pm.parent( 'thumbIK_ctrl_R','thumbIK_trs_R' )
pm.parent( 'thumbIK_ctrl_RT','thumbIK_trs_RT' )
pm.parent( 'lowArmIK_ctrl_R','lowArmIK_trs_R' )
pm.parent( 'handIK_grp_RT','handIK_grp_R' )
pm.parent( 'littleIK_grp_R','ringIK_grp_R','middleIK_grp_R','indexIK_grp_R','thumbIK_grp_R','handIK_grp_RT')

#IKハンドル入れ込み
pm.parent('ankie_ikHandle_LT','ankie_ikHandle_L','peelHell_grp_L')
pm.parent('foot_ikHandle_LT','foot_ikHandle_L','toeTap_grp_L')
pm.parent('ankie_ikHandle_RT','ankie_ikHandle_R','peelHell_grp_R')
pm.parent('foot_ikHandle_RT','foot_ikHandle_R','toeTap_grp_R')

pm.parent( 'hand_ikHandle_LT','hand_ikHandle_L','handIK_grp_LT')
pm.parent( 'thumb_ikHandle_L','thumbIK_grp_L')
pm.parent( 'index_ikHandle_L','indexIK_grp_L')
pm.parent( 'middle_ikHandle_L','middleIK_grp_L')
pm.parent( 'ring_ikHandle_L','ringIK_grp_L')
pm.parent( 'little_ikHandle_L','littleIK_grp_L')
pm.parent( 'hand_ikHandle_RT','hand_ikHandle_L','handIK_grp_RT')
pm.parent( 'thumb_ikHandle_R','thumbIK_grp_R')
pm.parent( 'index_ikHandle_R','indexIK_grp_R')
pm.parent( 'middle_ikHandle_R','middleIK_grp_R')
pm.parent( 'ring_ikHandle_R','ringIK_grp_R')
pm.parent( 'little_ikHandle_R','littleIK_grp_R')